title: Intrinsic - AI for Industry Challenge
description: How we used vision and force feedback to insert networking and fiber-optic connectors with a robot.
theme: jekyll-theme-cayman
show_downloads: false
url: https://satyaa27.github.io
baseurl: /vision-force-cable-insertion
